#!/bin/bash 
DIR="/media/hdd2/LOG"
BACKUP_DIR="/media/hdd3/BACK_UP"
p=70.000
freespace=`df -m | grep "/dev/vdb1" | awk '{print $4}'` 
b=$(bc<<<"scale=3;$freespace/1024") 
b1=$(bc<<<"scale=3;$b*100")
b2=$(bc<<<"scale=3;100-$b1")
echo "percent occupied is "$b2"%"

if [ $(echo "$b2 > $p" | bc) ]

then 
	N=5
	FILES=$(ls -tp $DIR | grep -v / | tail -n +2)
        FILES_TO_ARCHIVE=$(echo ${FILES} | tr '\n' ' ' | awk "{for(i=1;i<=N;i++) print $i}")
        FILES_TO_ARCHIVE2=("${FILES_TO_ARCHIVE[@]:0:$N}")
 	tar -czvf $BACKUP_DIR/$(date +%F_%H.%M.%S)_backup.tar.gz "${FILES_TO_ARCHIVE2[@]/#/$DIR}"
	rm -f $(echo ${FILES_TO_ARCHIVE2})
fi
